<?php
/**
 * Created by PhpStorm.
 * User: 魏巍 jswei30@gmail.com
 * Date: 2016/10/11
 * Time: 16:57
 **/

namespace Home\Controller;
use Think\Controller;

class NewsController extends BaseController{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->current = session('now_nav_first');
    }
    /**
     * [index 显示内容]
     * @return [type] [description]
     */
    public function index(){
        $id=$this->current['name'];
        $id = M('column')->field('id,title')->where(array('name'=>$id))->find();
        $map['column_id']=$id['id'];
        $map['status']=0;

        switch ($this->current['type']){
            case 1:
            case 2:
                $order = 'sort asc,create_time desc';
                $list = $this->getlist(M('article'),$map,$order,'');
                $this->list = $list;
                break;
            case 3:
                $this->list  = $list =  M('article')->field('id,content')->where($map)->find();
                break;
            case 5:
                $form = "<form class=\"form-horizontal\" id=\"form1\" role=\"form\" action=\"{U('/addform')}\" method=\"post\" autocomplete=\"off\">\n\t";
                $list =  M('form')->field('dates',true)->where($map)->select();
                
                foreach ($list as $k => $v) {
                    $placeholder = !empty($v['tooltips'])?$v['tooltips']:$v['title'];
                   
                    // if($v['type']==4 || $v['type']==5){
                    //     $list[$k]['items'] = explode(',',$v['items']);
                    // }
                    if($v['type']==1){
                        $form .= "<input type=\"text\" name=\"{$v['name']}\" placeholder=\"{$placeholder}\" class=\"form-control\">\n\t";
                    }else if($v['type']==2){
                        $form .= "<input type=\"number\" name=\"{$v['name']}\" placeholder=\"{$placeholder}\" class=\"form-control\">\n\t";
                    }else if($v['type']==3){
                        $form .= "<input type=\"number\" name=\"{$v['name']}\" placeholder=\"{$placeholder}\" class=\"form-control\">\n\t";
                    }else if($v['type']==4){
                        $_temp = explode(',',$v['items']);
                        foreach ($_temp as $k1 => $v1) {
                            $form .= "<div class=\"radio-inline\">\t\n";
                            $form .="\t\t<label class=\"\" style=\"font-weight:normal;\"><input type=\"radio\" value=\"{$k1}\" name=\"{$v['name']}\"";
                            if(!$k1){
                                $form .="checked=\"checked\">";
                            }
                            $form .="{$v1}</label>\t\n\t</div>\t\n\t";
                        }
                    }else if(){
                            
                    }
                   
                }
                 p($form);die;
                $con =<<<STR
<form class="form-horizontal" id="form1" role="form" action="__URL__/addform" method="post" autocomplete="off">
                        <volist name="list" id="vo">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{$vo['title']}</label>
                                <div class="col-sm-4">
                                   <eq name="vo.type" value="1">
                                       <input type="<eq name='vo.type' value='1'>text</eq><eq name='vo.type' value='2'>number</eq><eq name='vo.type' value='3'>text</eq>" name="{$vo['name']}" placeholder="<notempty name="vo.tooltips">{$vo['tooltips']}<else />{$vo['title']}</notempty>" class="form-control" autocomplete="off">
                                   </eq>
                                   <eq name="vo.type" value="4">
                                        <volist name="vo.items" id="ra">
                                            <div class="radio-inline">
                                                <label class="" style="font-weight:normal;">
                                                    <input type="radio" value="{$key}" name="{$vo['name']}" <eq name="key" value="0">checked="checked"</eq>>{$ra}
                                                </label>
                                            </div>
                                        </volist>
                                   </eq>
                                   <eq name="vo.type" value="5">
                                        <volist name="vo.items" id="ck">
                                            <div class="checkbox-inline">
                                                <label class="" style="font-weight:normal;">
                                                    <input type="checkbox" value="{$ck}"name="{$vo['name']}[]">{$ck}
                                                </label>
                                            </div>
                                        </volist>
                                   </eq>
                                   <eq name="vo.type" value="6">
                                       <textarea  class="form-control" name="{$vo['name']}" placeholder="<notempty name="vo.tooltips">{$vo['tooltips']}<else />{$vo['title']}</notempty>" rows="5"></textarea>
                                   </eq>
                                </div>
                            </div>
                        </volist>
                        <input type="hidden" name="m" value="{$_REQUEST['id']}">
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-info">提交</button>
                            </div>
                        </div>
                    </form>
STR;
                $this->assign('submit_forms',$con);
                $this->tpl='form';
                break;
        }
        $this->carousel = $this->get_site_carousel();
        $this->display($this->tpl);
    }
    /**
     * [detail 详细内容]
     * @param  integer $aid [description]
     * @return [type]       [description]
     */
    public function detail($aid=0){
        if($aid){
            $m = D('Article');
            $detail = $m->field('gid',true)->find($aid);
            $m->set_hits($detail['id']);
            $this->prev = $prev = $m->get_pre($detail['id'],$detail['column_id']);
            $this->next =$next = $m->get_next($detail['id'],$detail['column_id']);
            $c = $m->get_colunm($detail['column_id']);
            $detail['column'] = $c['title'];
            $this->article=$detail;
            $this->display('details');
        }
        
    }
    /**
     * 获取分页数据
     * @param type $model模型名(默认获取当前model)
     * @param type $map条件
     * @param type $order排序
     * @param type $field需要查询的字段，默认全部
     * @param type $pagination为每页显示的数量，默认为配置中的值
     * @return type返回结果数组
     */
    protected function getlist($model = '', $map = '', $order = '',$group = '', $pagination = '', $field = '*') {

        $model=!empty($model)?$model:M(CONTROLLER_NAME);
        $count = $model->where($map)->cache(true)->group($group)->count('*');
        $pagination = $pagination ? $pagination : C('PAGE_SIZE');

        $p = new \Think\Page($count, $pagination,array('url'=>'/'.$_GET['id']?$_GET['id']:'news'));
        $p->setConfig('header', '<a class="rows">当前 %NOW_PAGE%/%TOTAL_PAGE%页</a>');
        $p->setConfig('prev', '上一页');
        $p->setConfig('next','下一页');
        $p->setConfig('last', '最后一页');
        $p->setConfig('first','第一页');
        $p->setConfig('theme', '%UP_PAGE%%HEADER%%DOWN_PAGE%');
        $p->prevClass="pull-left";
        $p->nextClass="pull-right";
        $p->pageTheme="pagination";
        $p->allShow = 1;
        $show=$p->show1();
        $this->assign('page', $show);
        $res = $model->where($map)->cache(true)->field($field)->group($group)->limit($p->firstRow . ',' . $p->listRows)->order($order)->select();

        return $res;
    }
}